/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:bdc707eb-1986-41ba-ad54-07ad57fbaef2",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_N2LU1Z8Ew",
    "aws_user_pools_web_client_id": "1m90ts93qp0ea8cfv9jahf7noe",
    "oauth": {},
    "aws_user_files_s3_bucket": "nora185141-dev",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://rnexqetzvzct7lx35oodbub2vu.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
